Fix version check in ActiveRecord adapter
Fix version check in ActiveRecord adapter: the "target" version for comparison needs to be a string.

Fixes: 
ArgumentError: comparison of Gem::Version with 7.2 failed